export const quoteCopy = {
  pl: {
    privateOffer: "Oferta dla Ciebie",
    offer: "Oferta",
    preparedFor: "Przygotowana dla",
    preparedBy: "Przygotowana przez",
    issued: "Data wystawienia",
    valid: "Ważna do",
    intro: "O projekcie",
    scope: "Zakres współpracy",
    timeline: "Plan realizacji",
    packageTitle: "Wybierz swój zakres",
    packageIntro:
      "Wybierz wariant, aby zobaczyć pełną wycenę. Dodatki możesz dobrać poniżej.",
    packageFixed: "Wybrany wariant",
    recommended: "Rekomendowany",
    selected: "Wybrany",
    net: "netto",
    gross: "brutto",
    addons: "Dodatkowe możliwości",
    addonsIntro: "Rozszerz zakres o elementy, których potrzebujesz.",
    includedAddons: "Wybrane dodatki",
    optional: "Dodatek",
    breakdown: "Twoja wycena",
    service: "Usługa / zakres",
    quantity: "Ilość",
    unitPrice: "Cena jedn. netto",
    lineNet: "Wartość netto",
    vat: "VAT",
    lineGross: "Wartość brutto",
    taxRate: "Stawka VAT",
    subtotal: "Przed rabatem",
    discount: "Rabat",
    totalNet: "Razem netto",
    totalVat: "Razem VAT",
    totalGross: "Łączna kwota brutto",
    priceFor: "Cena za wybrany zakres",
    allPrices:
      "Kwoty uwzględniają wybrany wariant, dodatki i rabat. VAT naliczany jest dla każdej pozycji.",
    discounted: "Ceny wariantów i dodatków uwzględniają rabat.",
    pdf: "Pobierz ofertę PDF",
    pdfHelp: "PDF zawiera aktualnie wybrany wariant i dodatki.",
    pdfAccepted: "PDF zawiera zaakceptowaną wersję oferty.",
    acceptLink: "Przejdź do akceptacji",
    assumptions: "Założenia",
    exclusions: "Poza zakresem",
    paymentTerms: "Warunki płatności",
    notes: "Dodatkowe informacje",
    terms: "Warunki współpracy",
    acceptance: "Zaczynamy współpracę?",
    acceptanceIntro:
      "Przed akceptacją sprawdź wybrany wariant, dodatki oraz warunki oferty.",
    name: "Imię i nazwisko",
    email: "Adres e-mail",
    consent:
      "Zapoznałem/am się z ofertą i jej warunkami. Akceptuję wskazany zakres oraz łączną kwotę brutto",
    accept: "Akceptuję ofertę",
    accepting: "Zapisywanie akceptacji…",
    accepted: "Oferta zaakceptowana",
    acceptedIntro:
      "Zapisaliśmy Twoją decyzję. Poniżej znajduje się zaakceptowany zakres i kwota.",
    acceptedBy: "Zaakceptowana przez",
    acceptedDate: "Data akceptacji",
    acceptedWaiting: "Akceptacja została zapisana. Odświeżamy potwierdzenie…",
    acceptanceNote:
      "Akceptacja zapisuje tę wersję oferty wraz z wybranym zakresem i kwotą.",
    expired: "Termin ważności oferty minął",
    expiredHelp:
      "Aby potwierdzić aktualne warunki i termin realizacji, skontaktuj się z osobą, która przygotowała ofertę.",
    stale:
      "Oferta została zmieniona lub już zaakceptowana. Odśwież stronę i sprawdź aktualną wersję przed podjęciem decyzji.",
    sessionError: "Sesja wygasła. Odśwież stronę i ponownie wpisz hasło.",
    genericError:
      "Nie udało się zapisać akceptacji. Spróbuj ponownie za chwilę.",
    networkError:
      "Nie udało się połączyć. Sprawdź połączenie i spróbuj ponownie.",
    refresh: "Odśwież ofertę",
    contact: "Porozmawiajmy o ofercie",
    contactHelp:
      "Chcesz doprecyzować zakres lub ustalić kolejny krok? Napisz do mnie.",
    lock: "Zamknij dostęp",
    locking: "Zamykanie…",
    lockError: "Nie udało się zamknąć dostępu. Spróbuj ponownie.",
    confidential: "Oferta przygotowana indywidualnie",
    afterDiscount: "po rabacie",
  },
  en: {
    privateOffer: "Your proposal",
    offer: "Proposal",
    preparedFor: "Prepared for",
    preparedBy: "Prepared by",
    issued: "Date issued",
    valid: "Valid until",
    intro: "About the project",
    scope: "Scope of work",
    timeline: "Delivery plan",
    packageTitle: "Choose your scope",
    packageIntro:
      "Choose an option to see the full quote. You can include optional additions below.",
    packageFixed: "Selected option",
    recommended: "Recommended",
    selected: "Selected",
    net: "net",
    gross: "gross",
    addons: "Optional additions",
    addonsIntro: "Extend the scope with the services you need.",
    includedAddons: "Selected additions",
    optional: "Addition",
    breakdown: "Your quote",
    service: "Service / scope",
    quantity: "Quantity",
    unitPrice: "Net unit price",
    lineNet: "Net amount",
    vat: "VAT",
    lineGross: "Gross amount",
    taxRate: "VAT rate",
    subtotal: "Before discount",
    discount: "Discount",
    totalNet: "Total net",
    totalVat: "Total VAT",
    totalGross: "Total including VAT",
    priceFor: "Price for the selected scope",
    allPrices:
      "Amounts include your selected option, additions and discount. VAT is calculated for each line item.",
    discounted: "Option and addition prices include the discount.",
    pdf: "Download proposal PDF",
    pdfHelp: "The PDF includes your currently selected option and additions.",
    pdfAccepted: "The PDF includes the accepted version of this proposal.",
    acceptLink: "Review and accept",
    assumptions: "Assumptions",
    exclusions: "Outside the scope",
    paymentTerms: "Payment terms",
    notes: "Additional information",
    terms: "Working together",
    acceptance: "Ready to work together?",
    acceptanceIntro:
      "Before accepting, review your selected option, additions and the terms of this proposal.",
    name: "Full name",
    email: "Email address",
    consent:
      "I have read the proposal and its terms. I accept the selected scope and the total including VAT of",
    accept: "Accept proposal",
    accepting: "Saving acceptance…",
    accepted: "Proposal accepted",
    acceptedIntro:
      "Your decision has been recorded. The accepted scope and amount are shown below.",
    acceptedBy: "Accepted by",
    acceptedDate: "Date accepted",
    acceptedWaiting:
      "Your acceptance has been recorded. Refreshing the confirmation…",
    acceptanceNote:
      "Acceptance records this version of the proposal, your selected scope and the amount.",
    expired: "This proposal has expired",
    expiredHelp:
      "Please contact the person who prepared the proposal to confirm current terms and availability.",
    stale:
      "This proposal has changed or has already been accepted. Refresh the page and review the current version before deciding.",
    sessionError:
      "Your session has expired. Refresh the page and enter the password again.",
    genericError:
      "Your acceptance could not be saved. Please try again in a moment.",
    networkError: "Connection failed. Check your connection and try again.",
    refresh: "Refresh proposal",
    contact: "Let’s talk about your proposal",
    contactHelp:
      "Have a question about the scope or the next step? Get in touch.",
    lock: "Close access",
    locking: "Closing…",
    lockError: "Access could not be closed. Please try again.",
    confidential: "Prepared exclusively for you",
    afterDiscount: "after discount",
  },
} as const;
